Repository OS2626/SSGMCE_Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#7 Added references in cpp.
  C++/references.cpp
Labels: enhancement, help wanted, hachtoberfest-accepted

#8 Sorting_in_java
  SORTING_ALGO/merge_sort_in_java
Labels: enhancement, help wanted, hachtoberfest-accepted

#9 Update in Contributions
  CONTRIBUTING.md
Labels: documentation, hachtoberfest-accepted

#11 Cyclic rotate array
  Cyclic rotate array
Labels: documentation, enhancement, help wanted, hachtoberfest-accepted

#6 Revert "Added patterns printing"
  Patterns/butterfly.cpp
  Patterns/charequilateral.cpp
  Patterns/charinvertedtraingle.cpp
  Patterns/chartraingle.cpp
  Patterns/continuoustraingle.cpp
  Patterns/diamond.cpp
  Patterns/equilateraltraingle.cpp
  Patterns/halfrhombus.cpp
  Patterns/hollowrhombus.cpp
  Patterns/hollowsquare.cpp
  Patterns/invertedequilateraltraingle.cpp
  Patterns/invertedtraingle.cpp
  Patterns/invertedtraingle2.cpp
  Patterns/newtraingle.cpp
  Patterns/numbertraingle.cpp
  Patterns/numbertraingle2.cpp
  Patterns/samechartraingle.cpp
  Patterns/square.cpp
  Patterns/triangle.cpp
  Patterns/valley.cpp
  Patterns/zeroone.cpp
  SORTING_ALGO/bubbleSort.cpp
  SORTING_ALGO/insertionSort.cpp
  SORTING_ALGO/mergeSort.cpp
  SORTING_ALGO/quickSort.cpp
  SORTING_ALGO/selectionSort.cpp
Labels: documentation, enhancement, help wanted, hachtoberfest-accepted

#17 Insertion_sort
  Java/Java_Sorting/Insertion_sort
Labels: enhancement, help wanted, hachtoberfest-accepted

#12 Fibonacci Series
  Fibonacci Series
Labels: enhancement, good first issue, hachtoberfest-accepted

#13 Added Merge Sorting Code
  SORTING_ALGO/MergeSorting.cpp
Labels: enhancement, good first issue, hachtoberfest-accepted

#20 Added name in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: help wanted, good first issue, hachtoberfest-accepted

#24 Update Kadane's Algorithm
  C++/Kadane's Algorithm
Labels: enhancement, good first issue, hachtoberfest-accepted

#23 Quark
  SORTING_ALGO/BubbleSorting.c
  SORTING_ALGO/Insertion_Sort.cpp
Labels: enhancement, good first issue, hachtoberfest-accepted

#19 Create Longest_Common_Subsequence.cpp
  C++/Longest_Common_Subsequence.cpp
Labels: help wanted, good first issue, hachtoberfest-accepted

#22 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement, good first issue, hachtoberfest-accepted

#26 Create KMP.cpp
  C++/KMP.cpp
Labels: enhancement, good first issue, hachtoberfest-accepted

#29 Adding ternary search file in cpp language
  C++/Ternary_Search.cpp
  CONTRIBUTING.md
Labels: hachtoberfest-accepted

#40 Quick Sort algorithm in data structures and algorithms using Python
  CONTRIBUTING.md
  python/Quick_sort_algorithm.py
Labels: help wanted, good first issue, hachtoberfest-accepted

#36 delete the middle element of linked list
  C++/DeleteMiddleOfLinkedList.cpp
Labels: enhancement, good first issue, hachtoberfest-accepted

#39 Create selection_sort.cpp
  SORTING_ALGO/selection_sort.cpp
Labels: good first issue, hachtoberfest-accepted

#38 Create vectorOfvector.cpp
  C++_STL/vectorOfvector.cpp
Labels: good first issue, hachtoberfest-accepted

#37 Rotate the linked list by k nodes
  C++/Rotate_linkedlist.cpp
Labels: good first issue, hachtoberfest-accepted

#35 Create NextGreaterElement
  C++/NextGreaterElement
Labels: enhancement, hachtoberfest-accepted

#34 Create LargestSubarrayWith0sum
  C++/LargestSubarrayWith0sum
Labels: enhancement, hachtoberfest-accepted

#41 Create doormat.py
  python/doormat.py
Labels: enhancement, hachtoberfest-accepted

#33 Create PeakElement
  C++/PeakElement
Labels: enhancement, hachtoberfest-accepted

#32 Reverse a linked list
  C++/Reverse_LinkedList.cpp
Labels: good first issue, hachtoberfest-accepted

#42 Create alphaRangoli.py
  python/alphaRangoli.py
Labels: good first issue, hachtoberfest-accepted

#31 Create SortAnArrayof0s,1sand2s
  C++/SortAnArrayof0s,1sand2s
Labels: help wanted, hachtoberfest-accepted

#30 Remove loop in a linked list
  C++/Remove_loop_from_linkedList.cpp
Labels: enhancement, hachtoberfest-accepted

#28 Create HeapSort.cpp
  SORTING_ALGO/HeapSort.cpp
Labels: good first issue, hachtoberfest-accepted

#27 Create SelectionSort.cpp
  SORTING_ALGO/SelectionSort.cpp
Labels: enhancement, good first issue, hachtoberfest-accepted

#43 Create analogClock.py
  python/analogClock.py
Labels: enhancement, hachtoberfest-accepted

#45 Matrix Multiplication.cpp
  C++/Matrix Multiplication.cpp
Labels: enhancement, good first issue, hachtoberfest-accepted
